// ============================================================================
// js/api-client.js - API Request Handlers for All Services
// ============================================================================

/**
 * Generate image from prompt using selected API
 */
async function generateImageFromPrompt(prompt) {
    try {
        if (selectedAPI === 'pollinations') {
            return await generateWithPollinations(prompt);
        } else if (selectedAPI === 'replicate') {
            return await generateWithReplicate(prompt);
        } else if (selectedAPI === 'stability') {
            return await generateWithStability(prompt);
        } else if (selectedAPI === 'openai') {
            return await generateWithOpenAI(prompt);
        }
        throw new Error('No API selected');
    } catch (error) {
        console.error('Error in generateImageFromPrompt:', error);
        throw error;
    }
}

/**
 * Generate image using Pollinations AI (FREE - No API Key)
 */
async function generateWithPollinations(prompt) {
    try {
        const encodedPrompt = encodeURIComponent(prompt);
        const imageUrl = `https://image.pollinations.ai/prompt/${encodedPrompt}?width=512&height=512&seed=${Math.random()}`;
        return imageUrl;
    } catch (error) {
        throw new Error('Failed to generate image with Pollinations: ' + error.message);
    }
}

/**
 * Generate image using Replicate API
 */
async function generateWithReplicate(prompt) {
    try {
        const apiKey = document.getElementById('replicate-key').value;
        if (!apiKey) {
            throw new Error('Replicate API key is required');
        }

        const response = await fetch('https://api.replicate.com/v1/predictions', {
            method: 'POST',
            headers: {
                'Authorization': `Token ${apiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                version: 'bf52fdf836b1f9a84b0a2abe8dd8e8c3a6cab2e9bbc65adf6e9d1c7b1d7f8e9a',
                input: {
                    prompt: prompt,
                    image_dimensions: '512x512'
                }
            })
        });

        if (!response.ok) {
            throw new Error('Replicate API error: ' + response.statusText);
        }

        const result = await response.json();
        
        // Poll for completion
        let prediction = result;
        let attempts = 0;
        const maxAttempts = 60;
        
        while ((prediction.status === 'processing' || prediction.status === 'starting') && attempts < maxAttempts) {
            await new Promise(resolve => setTimeout(resolve, 1000));
            const pollResponse = await fetch(`https://api.replicate.com/v1/predictions/${prediction.id}`, {
                headers: { 'Authorization': `Token ${apiKey}` }
            });
            prediction = await pollResponse.json();
            attempts++;
        }

        if (prediction.output && Array.isArray(prediction.output)) {
            return prediction.output[0];
        } else if (prediction.output) {
            return prediction.output;
        }
        
        throw new Error('No output from Replicate');
    } catch (error) {
        throw new Error('Failed to generate image with Replicate: ' + error.message);
    }
}

/**
 * Generate image using Stability AI API
 */
async function generateWithStability(prompt) {
    try {
        const apiKey = document.getElementById('stability-key').value;
        if (!apiKey) {
            throw new Error('Stability AI API key is required');
        }

        const response = await fetch('https://api.stability.ai/v1/generate', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                prompt: prompt,
                samples: 1,
                steps: 30,
                height: 512,
                width: 512
            })
        });

        if (!response.ok) {
            throw new Error('Stability AI error: ' + response.statusText);
        }

        const result = await response.json();
        if (result.artifacts && result.artifacts[0]) {
            return 'data:image/png;base64,' + result.artifacts[0].base64;
        }
        
        throw new Error('No image generated by Stability AI');
    } catch (error) {
        throw new Error('Failed to generate image with Stability AI: ' + error.message);
    }
}

/**
 * Generate image using OpenAI DALL-E API
 */
async function generateWithOpenAI(prompt) {
    try {
        const apiKey = document.getElementById('openai-key').value;
        if (!apiKey) {
            throw new Error('OpenAI API key is required');
        }

        const response = await fetch('https://api.openai.com/v1/images/generations', {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${apiKey}`,
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                prompt: prompt,
                n: 1,
                size: '512x512',
                model: 'dall-e-3'
            })
        });

        if (!response.ok) {
            throw new Error('OpenAI error: ' + response.statusText);
        }

        const result = await response.json();
        if (result.data && result.data[0] && result.data[0].url) {
            return result.data[0].url;
        }
        
        throw new Error('No image URL from OpenAI');
    } catch (error) {
        throw new Error('Failed to generate image with OpenAI: ' + error.message);
    }
}

/**
 * Analyze image using Hugging Face BLIP (FREE - No API Key)
 */
async function analyzeImageWithAI(imageUrl) {
    try {
        showMessage('🎯 Analyzing image with Hugging Face BLIP...', 'info');
        
        const response = await fetch('https://api-inference.huggingface.co/models/Salesforce/blip-image-captioning-large', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                inputs: imageUrl
            })
        });

        if (!response.ok) {
            throw new Error('Hugging Face API error: ' + response.statusText);
        }

        const result = await response.json();
        
        let description = '';
        if (Array.isArray(result) && result[0] && result[0].generated_text) {
            description = result[0].generated_text;
        } else if (result.generated_text) {
            description = result.generated_text;
        } else {
            throw new Error('No description returned');
        }

        // Create detailed analysis from description
        const analysis = `Image Recognition Results - Description: ${description}. 
Theme: ${detectThemeFromDescription(description)}.
Style: ${detectStyleFromDescription(description)}.
Tone & Atmosphere: ${detectToneFromDescription(description)}.
Suggested Variations: Create different artistic interpretations with varied lighting, color schemes, perspectives, seasons, and artistic styles.`;

        return analysis;
    } catch (error) {
        console.error('Hugging Face Analysis Error:', error);
        showMessage('⚠️ Using basic image analysis. ' + error.message, 'warning');
        return generateImageAnalysisWithFallback();
    }
}
